### ISSUE TITLE
Interfaz de Usuario-Registro-Validacion 2 integrantes

### ISSUE THREAD

**Issue by calderonperaza** [diseno2022/seus#20]
Se van a desarrollar los componentes para:
La bienvenida y el boton para iniciar sesion con google
la interfaz de verificación de usuario.
Recuerda también poner el captcha no soy un robot, solo como imagen porque estamos haciendo solo la interfaz

**Comment by avalos97** [comment]
cheverriaw21 me podrias pasar tu whatsapp?

**Comment by cheverriaw21** [comment]
7335 2392
